name: MQTT Gateway Client
version: "1.0.0"
slug: mqtt_gateway_client
description: MQTT gateway forwarding pool telemetry to Azure IoT Hub (might be used for other purposes as well)
boot: auto
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armv7

# homepage of the add-on
url: https://github.com/pattedala/Hass-Addons/MQTTGatewayClient-addon

options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""

  routes: []

schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str
  mqtt_password: password

  routes:
    - mqtt_topic: str
      iothub_connection_string: password

services:
  - mqtt