FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY app/MQTTGatewayClient.csproj app/

RUN dotnet restore app/MQTTGatewayClient.csproj

COPY app/ app/


RUN dotnet publish app/MQTTGatewayClient.csproj \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/runtime:10.0

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "MQTTGatewayClient.dll"]